name: 'Terraform Deployment'

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install jq if not present
        run: sudo apt-get install -y jq

      - name: Terraform Init
        run: terraform init -upgrade

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan

      - name: Verify and Output Terraform Outputs
        id: output
        run: |
          echo "Verifying and Outputting Terraform Outputs..."
          terraform output -json > tf_outputs.json

          echo "Raw content of tf_outputs.json:"
          cat tf_outputs.json

          echo "Validating JSON structure of tf_outputs.json:"
          jq empty tf_outputs.json

      - name: Parse Terraform Outputs and Set Environment Variables
        id: parse_outputs
        run: |
          if [ -f tf_outputs.json ]; then
            DB_USER=$(jq -r '.cosmosdb_username.value' tf_outputs.json)
            DB_PASSWORD=$(jq -r '.cosmosdb_password.value' tf_outputs.json)
            DB_HOST=$(jq -r '.cosmosdb_account_endpoint.value' tf_outputs.json)
            DB_NAME=$(jq -r '.cosmosdb_database_name.value' tf_outputs.json)
            echo "PROD_DB_USER=$DB_USER" >> $GITHUB_ENV
            echo "PROD_DB_PASSWORD=$DB_PASSWORD" >> $GITHUB_ENV
            echo "PROD_DB_HOST=$DB_HOST" >> $GITHUB_ENV
            echo "PROD_DB_NAME=$DB_NAME" >> $GITHUB_ENV
          else
            echo "tf_outputs.json file not found"
            exit 1

      - name: Configure App Service Environment Variables
        run: |
          az webapp config appsettings set --name nodejs-app-${{ steps.output.outputs.random_pet.name }} --resource-group myResourceGroup-${{ steps.output.outputs.random_pet.name }} --settings \
            PROD_DB_USER=${{ env.PROD_DB_USER }} \
            PROD_DB_PASSWORD=${{ env.PROD_DB_PASSWORD }} \
            PROD_DB_HOST=${{ env.PROD_DB_HOST }} \
            PROD_DB_NAME=${{ env.PROD_DB_NAME }} \
            NODE_ENV=production \
            WEBSITES_ENABLE_APP_SERVICE_STORAGE=false \
            PORT=80 \
            LOGGING_LEVEL=Verbose
