name: 'Terraform Deployment'

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set MongoDB Secrets
        run: |
          echo "prod_db_user = \"${{ secrets.PROD_DB_USER }}\"" >> terraform.tfvars
          echo "prod_db_password = \"${{ secrets.PROD_DB_PASSWORD }}\"" >> terraform.tfvars
          echo "prod_db_host = \"${{ secrets.PROD_DB_HOST }}\"" >> terraform.tfvars
          echo "prod_db_port = \"${{ secrets.PROD_DB_PORT }}\"" >> terraform.tfvars
          echo "prod_db_name = \"${{ secrets.PROD_DB_NAME }}\"" >> terraform.tfvars

      - name: Display terraform.tfvars
        run: cat terraform.tfvars

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
